name: Package Manager Builds

on: [push, pull_request]

jobs:
  conan_builds:
    name: Conan ${{matrix.conan_version}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-15, windows-2025]
        conan_version:
          - '1.63'
          - '2.1'

        include:
          - conan_version: '1.63'
            profile_command: 'conan profile new default --detect --force'
          - conan_version: '2.1'
            profile_command: 'conan profile detect --force'

    steps:
    - uses: actions/checkout@v6

    - name: Install conan
      run: pip install conan==${{matrix.conan_version}}

    - name: Detect a Clang-based Conan profile
      run: ${{ matrix.profile_command }}
      env:
        CC: clang
        CXX: clang++

    - name: Run conan package create
      run: conan create . -tf .conan/test_package
      env:
        CC: clang
        CXX: clang++
